name: Test
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/setup-jule@v1
        with:
          version: latest

      - name: Implementation Tests
        run: |
          julec test -o ldbtest .
          ./ldbtest

      - name: Use Tests
        run: |
          julec test -o ldbtest test
          ./ldbtest
